// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -destination=./mocks/contract.go -package=mock -source=contract.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	shortenedurl "url-shortener/internal/domain/shortenedurl"

	gomock "go.uber.org/mock/gomock"
)

// MockgetOriginalUrlService is a mock of getOriginalUrlService interface.
type MockgetOriginalUrlService struct {
	ctrl     *gomock.Controller
	recorder *MockgetOriginalUrlServiceMockRecorder
	isgomock struct{}
}

// MockgetOriginalUrlServiceMockRecorder is the mock recorder for MockgetOriginalUrlService.
type MockgetOriginalUrlServiceMockRecorder struct {
	mock *MockgetOriginalUrlService
}

// NewMockgetOriginalUrlService creates a new mock instance.
func NewMockgetOriginalUrlService(ctrl *gomock.Controller) *MockgetOriginalUrlService {
	mock := &MockgetOriginalUrlService{ctrl: ctrl}
	mock.recorder = &MockgetOriginalUrlServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgetOriginalUrlService) EXPECT() *MockgetOriginalUrlServiceMockRecorder {
	return m.recorder
}

// GetOriginalUrl mocks base method.
func (m *MockgetOriginalUrlService) GetOriginalUrl(ctx context.Context, short string) (*shortenedurl.ShortenedURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOriginalUrl", ctx, short)
	ret0, _ := ret[0].(*shortenedurl.ShortenedURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOriginalUrl indicates an expected call of GetOriginalUrl.
func (mr *MockgetOriginalUrlServiceMockRecorder) GetOriginalUrl(ctx, short any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginalUrl", reflect.TypeOf((*MockgetOriginalUrlService)(nil).GetOriginalUrl), ctx, short)
}
