// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -destination=./mocks/contract.go -package=mock -source=contract.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	shortenedurl "url-shortener/internal/domain/shortenedurl"

	gomock "go.uber.org/mock/gomock"
)

// MockShortenUrlService is a mock of ShortenUrlService interface.
type MockShortenUrlService struct {
	ctrl     *gomock.Controller
	recorder *MockShortenUrlServiceMockRecorder
	isgomock struct{}
}

// MockShortenUrlServiceMockRecorder is the mock recorder for MockShortenUrlService.
type MockShortenUrlServiceMockRecorder struct {
	mock *MockShortenUrlService
}

// NewMockShortenUrlService creates a new mock instance.
func NewMockShortenUrlService(ctrl *gomock.Controller) *MockShortenUrlService {
	mock := &MockShortenUrlService{ctrl: ctrl}
	mock.recorder = &MockShortenUrlServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortenUrlService) EXPECT() *MockShortenUrlServiceMockRecorder {
	return m.recorder
}

// ShortenUrl mocks base method.
func (m *MockShortenUrlService) ShortenUrl(ctx context.Context, url string) (*shortenedurl.ShortenedURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShortenUrl", ctx, url)
	ret0, _ := ret[0].(*shortenedurl.ShortenedURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShortenUrl indicates an expected call of ShortenUrl.
func (mr *MockShortenUrlServiceMockRecorder) ShortenUrl(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShortenUrl", reflect.TypeOf((*MockShortenUrlService)(nil).ShortenUrl), ctx, url)
}
